apiVersion: v1
kind: Service
metadata:
  name: feature-flag-demo-app-service
  labels:
    app: feature-flag-demo
spec:
  type: NodePort
  selector:
    app: feature-flag-demo
  ports:
    - port: 30000
      targetPort: 8080
      nodePort: 30000